### ISSUE TITLE
b'' around suggestions in some languages

### ISSUE THREAD

**Issue by wjt** [sugarlabs/words-activity#27]
When I search for source terms in English or German, I see suggestions with `b''` around them. This looks like a Python 3 porting problem, treating a `bytes` as a `str`.

![Capture d’écran de 2020-05-13 22-04-15](https://user-images.githubusercontent.com/86760/81865490-e554d900-9565-11ea-9069-eb85c5cc73a7.png)
![Capture d’écran de 2020-05-13 22-05-17](https://user-images.githubusercontent.com/86760/81865498-e71e9c80-9565-11ea-9ca9-d9dfdf86785b.png)

I don't see the same problem for other source languages that I have tried.

![Capture d’écran de 2020-05-13 22-05-33](https://user-images.githubusercontent.com/86760/81865499-e71e9c80-9565-11ea-8b20-f0e47ffa7a60.png)

I am using Words from Flathub https://github.com/flathub/org.sugarlabs.Words/commit/050411dcf0e9b29f923cf4e0facce53cc5f45903 on Endless OS.

**Comment by quozl** [comment]
Thanks.  I agree it looks like a Python 3 porting problem.  I've tried Words-24 and Words-23 and don't see this problem.  On the other hand no or very few suggestions are shown for English or Deutch, not like what you show.  I'm not sure if any of the changes in https://github.com/flathub/org.sugarlabs.Words/commit/050411dcf0e9b29f923cf4e0facce53cc5f45903 are responsible.

@tchx84, what do you think?

**Comment by tchx84** [comment]
Most likely Python3 port issue, ill take a look.

**Comment by srevinsaju** [comment]
I fixed it on #24, maybe the flatpak was not updated after that commit; #23 was the issue related to this.

**Comment by tchx84** [comment]
That was fast :) I am updating all apps on flathub*, btw. Words just happen to be last one in alphabetical order.

EDIT: ill prioritize it, of course hah.

**Comment by srevinsaju** [comment]
:)

**Comment by wjt** [comment]
Thanks!

(An Endless partner discovered this app and specifically cited it as a great new addition. Of course I explained we can take no credit. :smiley:)

**Comment by tchx84** [comment]
Updated. Should be deployed in a few hours. https://github.com/flathub/org.sugarlabs.Words/pull/1

> Thanks!
> 
> (An Endless partner discovered this app and specifically cited it as a great new addition. Of course I explained we can take no credit. )

Hey @wjt , you can show these to that partner as well ;) https://flathub.org/apps/search/sugarlabs

**Comment by quozl** [comment]
Is there a way to install a collection of Sugar activities on Endless OS?

**Comment by wjt** [comment]
Something like this? :-)

```bash
flatpak remote-ls --system --columns application flathub \
  | grep '^org.sugarlabs.'
  | xargs flatpak install --system -y flathub
```

**Comment by srevinsaju** [comment]
@quozl @chimosky @tchx84 I hope this issue can be closed.
